FROM node:24.14.0 AS build
WORKDIR /src

# install dependencies
COPY Client/package*.json ./
RUN npm install

# copy app files
COPY Client .

# build app
RUN npm run build -- --configuration production

FROM nginx:alpine AS runtime

# config nginx
COPY Client/nginx.conf /etc/nginx/conf.d/default.conf

# remove defautl html file
RUN rm -rf /usr/share/nginx/html/*

# copy published app from build
COPY --from=build /src/dist/Client/browser /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]

