FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# restore dependencies
COPY TaskManagement/TaskManagement.csproj ./
RUN dotnet restore TaskManagement.csproj

# copy all project files in app/src folder
COPY TaskManagement .

# build and publish the application in publish
RUN dotnet build TaskManagement.csproj -c Release
RUN dotnet publish TaskManagement.csproj -c Release -o publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

# copy the published application from the build stage
COPY --from=build /src/publish .

ENTRYPOINT ["dotnet", "TaskManagement.dll"]