name: CI/CD

on:
   workflow_dispatch:
   push:
     branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v6.0.2

    - name: setup dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0

    - name: restore, build, and publish
      run: |
        dotnet restore TaskManagement/TaskManagement.csproj
        dotnet build TaskManagement/TaskManagement.csproj -c Release --no-restore
        dotnet publish TaskManagement/TaskManagement.csproj -c Release -o TaskManagement/publish --no-restore --no-build

    - name: upload published files to artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-artifact
        path: TaskManagement/publish
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: download published files from artifact
      uses: actions/download-artifact@v4
      with:
        name: api-artifact
        path: .
   
    - name: deploying
      run: echo application deployed successfully

  docker:
     needs: build
     runs-on: ubuntu-latest

     steps:
        - name: checkout code
          uses: actions/checkout@v6.0.2

        - name: docker login
          uses: docker/login-action@v4.0.0
          with:
            username: ${{secrets.DOCKERUSER}}
            password: ${{secrets.DOCKERPASSWORD}}

        - name: build and push the image
          run: |
             docker compose build
             docker compose push






    
